name: flow-with-norm-build-tests

on:
  push:
      branches:
        - main

jobs:
  norminette:
    name: norminette
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: install dependencies 
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install norminette 
      
      - name: Test with norminette
        run: norminette

  build:
    name: build
    needs: norminette
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      
      - name: Make Mandatory
        run: make
      
      - name: Make Bonus
        run: make bonus
  
  test01:
    name: Test Tripouille - Mandatory
    needs: build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2

      - name: install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install valgrind -y

      - name: Cloning Tester Tripouille - Mandatory
        run: |
          git clone https://github.com/Tripouille/libftTester.git
          cd libftTester
          export TERM=xterm-256color
          make m
      
      - name: Bonus List New
        run: make lstnew

      - name: Bonus List Add Front
        run: make lstadd_front

      - name: Bonus List Size
        run: make lstsize

      - name: Bonus List Last
        run: make lstlast

      - name: Bonus List Add Back
        run: make lstadd_back

# test02:
#   name: Test Tripouille - Bonus
#   needs: test01
#   runs-on: ubuntu-20.04
#   defaults:
#     run:
#       working-directory: .
#   steps:
#     - uses: actions/checkout@v2

#     - name: install Valgrind
#       run: |
#         sudo apt-get update
#         sudo apt-get install valgrind -y

#     - name: Cloning Tester Tripouille - Bonus
#       run: |
#         git clone https://github.com/Tripouille/libftTester.git
#         cd libftTester
#         export TERM=xterm-256color
    
#     - name: Bonus List New
#       run: make lstnew

#     - name: Bonus List Add Front
#       run: make lstadd_front

#     - name: Bonus List Size
#       run: make lstsize

#     - name: Bonus List Last
#       run: make lstlast

#     - name: Bonus List Add Back
#       run: make lstadd_back